### DISCUSSION TITLE
auto ingest not working with hardlinks?

### DISCUSSION THREAD

**Discussion by arpitgupta** [crocodilestick/Calibre-Web-Automated#370] [General]
So recently I am seeing new files I add in the ingest directory are not getting processed automatically. I recently switched to using hardlinks to copy files over to the ingest directory. Here is my compose file

```
cwa:
    <<: *common
    image: crocodilestick/calibre-web-automated:latest
    container_name: cwa
    environment:
      <<: *env
    volumes:
      - ${BASE_DOCKER_DATA_PATH}/calibre-web-automated:/config 
      - /htpc/media/calibre-web-automated/ingest:/cwa-book-ingest
      - /htpc/media/calibre-web-automated/library:/calibre-library
 ```

Ingest directory is on a zfs dataset. This same process was working when i was not using hardlinks. If I refresh the library from the UI it process the files just fine.

I am running more tests to confirm if it is hardlinks that cause the issue or if its something else.

Edit: can confirm hardlinks causes the issue.
