### ISSUE TITLE
[Feature Request][Bug] Installation on Kubernetes respecting securityContext (rootless)

### ISSUE THREAD

**Issue by fgeck** [crocodilestick/Calibre-Web-Automated#167]
Hello,

I am not sure if I should label this issue as a Feature Request or a Bug, therefore adding both.
I am trying to run CWA in my homelab kubernetes cluster **respecting the securityContext configuration**.

The recommended way to run apps in K8s is to run them as non-root, which can be done via securityContext (see deployment at the end
As this enforces that containers are running as non-root, CWA fails to start:

```log
kubectl logs calibre-wa-6987594778-xrrkn
s6-overlay-suexec: warning: unable to gain root privileges (is the suid bit set?)
s6-mkdir: warning: unable to mkdir /run/s6: Permission denied
s6-mkdir: warning: unable to mkdir /run/service: Permission denied
s6-overlay-suexec: fatal: child failed with exit code 111
```

From my understanding it is not needed to do the `chown` as Kubernetes is taking care of the filesystem permissions (see `fsGroup` and `fsGroupChangePolicy` in [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)).
I am asking either for help on how to fix this, or would like to request the "feature" rootless docker image, so that it is possible to run the container without root.
I assume this is possible with overwriting the entrypoint to be not the standard linuxserver.io one, but I guess also in the Dockerfile of CWA there are modifications needed to install all dependencies (especially the ones linuxserver.io would download) so that finally it is able to skip the linuxserver.io init process.

I had a look at #30 but it did not solve my issue.

Kubernetes deployment (I left out some unnecessary parts like liveness probes etc.)
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: calibre-wa
  name: calibre-wa
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: calibre-wa
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calibre-wa
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: main
        env:
        - name: TZ
          value: Europe/Berlin
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: DOCKER_MODS
          value: "lscr.io/linuxserver/mods:universal-calibre-v7.16.0"
        image: crocodilestick/calibre-web-automated:V2.1.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
          name: main
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: calibre-wa-config
        - mountPath: /calibre-library
          name: calibre-library
        - mountPath: /cwa-book-ingest
          name: cwa-book-ingest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      volumes:
      - name: calibre-wa-config
        persistentVolumeClaim:
          claimName: calibre-wa-config-pvc
      - name: calibre-library
        persistentVolumeClaim:
          claimName: calibre-library-pvc
      - name: cwa-book-ingest
        persistentVolumeClaim:
          claimName: calibre-wa-book-ingest-pvc

```
