### ISSUE TITLE
[bug] Kobo Sync - Generated API using FQDN yields "HTTP" vs "HTTPS" endpoints + Message box is also misaligned on caliBlur! Dark Theme

### ISSUE THREAD

**Issue by jadehawk** [crocodilestick/Calibre-Web-Automated#191]
**Describe the bug**
Kobo Sync - Generated API using CWA hosted on an FQDN yields "**HTTP**" vs "**HTTPS**" endpoints:
_We get this:_
`api_endpoint=http://xxxxx.xxx/12345`
**_instead of:_**
`api_endpoint=https://xxxxx.xxx/12345`

And the same message box that displays this API/Token is not aligned correctly and looks out of place when using the caliBlur! Dark Theme.
Message box looks perfect in the standard Theme. Tested on Latest Chrome/Brave/Edge Browsers.

Manually changing the **HTTP** to **HTTPS** on the `api_endpoint=http` is all that is needed and Kobo Sync works without an issues.

**To Reproduce**
1. Go to 'PROFILE'
2. Click on 'Create Kobo Token'
3. See error

**Expected behavior**
Nice and Aligned message box containing the correct `api_endpoint`. When hosting CWA on a FQDN (TLS) and using the nice caliBlur! Dark Theme.

**Screenshots**

![Image](https://github.com/user-attachments/assets/4025ba1b-6d79-46a7-a7d7-ea04835b4ebd)

**Configuration(please complete the following information):**
 - OS: [Debian 12, Proxmox 8]
 - Hardware: [x86 server]

**Comment by demitrix** [comment]
Dug into this a bit, looks like the issue stems from the headers Calibre-Web is using to check scheme. This may be a better fit for an upstream issue. In the mean time, if you configure your reverse proxy to send https in the X-Scheme header then it will be fixed. IMHO this header should be changed out for HTTP_X_FORWARDED_PROTO which is more common. Tested this here and it solved the issue. We'll let @crocodilestick weigh in on this.

**Comment by jadehawk** [comment]
> Dug into this a bit, looks like the issue stems from the headers Calibre-Web is using to check scheme. This may be a better fit for an upstream issue. In the mean time, if you configure your reverse proxy to send https in the X-Scheme header then it will be fixed. IMHO this header should be changed out for HTTP_X_FORWARDED_PROTO which is more common. Tested this here and it solved the issue. We'll let [@crocodilestick](https://github.com/crocodilestick) weigh in on this.

@demitrix

I gave up on this. I tried to get your solution to work but I can't get it setup properly using "Traefik" I figure this setup is correct as I get no errors but the returning api still shows as "http". here is what the "middleware" is set to, maybe you have some experience with "Traefik" as a reverse proxy. 
Thank you for your troubleshooting.

I logged in to my cwa instance using a private window, deleted kobo api and regenerated a new one each time and always received the api as http.

The commented-out parts are variations I tried that also did not work.

calibre-web-automated.yml
``` yaml

http:
  routers:
    CWA:
      entryPoints:
        - websecure
      service: CWA
      rule: Host(`mycwainthewild.com`)
      tls: true
      middlewares:
        - "CWA-Headers"

  services:
    CWA:
      loadBalancer:
        servers:
          - url: http://10.147.250.106:8084


  middlewares:
    CWA-Headers:
      headers:
        customResponseHeaders:
          HTTP_X_FORWARDED_PROTO: "https"
          #HTTP-X-Forwarded-Proto: "https"
          #X-Forwarded-Proto: "https"
        customRequestHeaders:
          HTTP_X_FORWARDED_PROTO: "https"
          #HTTP-X-Forwarded-Proto: "https"
          #X-Forwarded-Proto: "https"
          

```

**Comment by demitrix** [comment]
> > Dug into this a bit, looks like the issue stems from the headers Calibre-Web is using to check scheme. This may be a better fit for an upstream issue. In the mean time, if you configure your reverse proxy to send https in the X-Scheme header then it will be fixed. IMHO this header should be changed out for HTTP_X_FORWARDED_PROTO which is more common. Tested this here and it solved the issue. We'll let [@crocodilestick](https://github.com/crocodilestick) weigh in on this.
> 
> @demitrix
> 
> I gave up on this. I tried to get your solution to work but I can't get it setup properly using "Traefik" I figure this setup is correct as I get no errors but the returning api still shows as "http". here is what the "middleware" is set to, maybe you have some experience with "Traefik" as a reverse proxy. 
> Thank you for your troubleshooting.
> 
> I logged in to my cwa instance using a private window, deleted kobo api and regenerated a new one each time and always received the api as http.
> 
> The commented-out parts are variations I tried that also did not work.
> 
> calibre-web-automated.yml
> ``` yaml
> 
> http:
>   routers:
>     CWA:
>       entryPoints:
>         - websecure
>       service: CWA
>       rule: Host(`mycwainthewild.com`)
>       tls: true
>       middlewares:
>         - "CWA-Headers"
> 
>   services:
>     CWA:
>       loadBalancer:
>         servers:
>           - url: http://10.147.250.106:8084
> 
> 
>   middlewares:
>     CWA-Headers:
>       headers:
>         customResponseHeaders:
>           HTTP_X_FORWARDED_PROTO: "https"
>           #HTTP-X-Forwarded-Proto: "https"
>           #X-Forwarded-Proto: "https"
>         customRequestHeaders:
>           HTTP_X_FORWARDED_PROTO: "https"
>           #HTTP-X-Forwarded-Proto: "https"
>           #X-Forwarded-Proto: "https"
>           
> 
> ```
> 
> 

I do use traefik but haven't messed with custom headers. Looks like though you added the wrong header. Calibre-web is expecting "X-Scheme" to contain "https". Try adding that as a custom header.

**Comment by jadehawk** [comment]
Yep that did it.
I wish I was smart enough to figure this out, but I thank you for finding the solution.
Now it's working like it should.

calibre-web-automated.yml

``` yaml

http:
  routers:
    CWA:
      entryPoints:
        - websecure
      service: CWA
      rule: Host(`mycwainthewild.com`)
      tls: true
      middlewares:
        - "CWA-Headers"

  services:
    CWA:
      loadBalancer:
        servers:
          - url: http://10.147.250.106:8084


  middlewares:
    CWA-Headers:
      headers:
        customRequestHeaders:
          X-Scheme: "https"

```
