### ISSUE TITLE
[bug] Unable to start CWA on port 80

### ISSUE THREAD

**Issue by alexindigo** [crocodilestick/Calibre-Web-Automated#291]
**Describe the bug**
Updated CWA Basic Setting to change http port `8083` to `80`. It saved it correctly, but service didn't start, also tried to restart docker container, still seeing the same logs:

```
[Errno 13] Permission denied: ('', 80)
```

Other docker containers don't have issues with utilizing port 80.

For example `advplyr/audiobookshelf` works fine on port 80, with the same docker setup: macvlan, and dedicated ip address.

**To Reproduce**
1. Start docker container with CWA
2. Update Basic settings to use port 80
3. Save
4. Observe Web UI isn't responding and error in the logs.

**Expected behavior**
Expected for the web ui to be able to listen on port 80 within docker container.

**Screenshots**
N/A

**Configuration(please complete the following information):**
 - OS: Synology
 - Hardware: x86 / Synology NAS
 - Version: DSM 7.2.1

**Additional context**
I'm using macvlan networking for all my docker containers:

```
networks:
  lan:
    name: lan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.4.10.1/24"
          ip_range: "10.4.10.1/24"
          gateway: "10.4.10.1"
```

and dedicate ip address for CWA container:

```
    networks:
      lan:
        ipv4_address: 10.4.10.98
```
