### ISSUE TITLE
[bug] Synology - hitting inotify.max_user_watches limit

### ISSUE THREAD

**Issue by 2770862886** [crocodilestick/Calibre-Web-Automated#311]
**Describe the bug**
Repeat the log of 
```
========== STARTING CWA-INGEST SERVICE ==========

========== STARTING METADATA CHANGE DETECTOR ===========

[metadata-change-detector] Watching folder: /app/calibre-web-automated/metadata_change_logs

[cwa-ingest-service] Watching folder: /cwa-book-ingest

Setting up watches.

Failed to watch /app/calibre-web-automated/metadata_change_logs; upper limit on inotify watches reached!

Please increase the amount of inotify watches allowed per user via `/proc/sys/fs/inotify/max_user_watches'.
```
**To Reproduce**
with the docker-compose:
```
version: "3"

services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      # Only change these if you know what you're doing
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /volume2/docker/calibre-web/config:/config
      - /volume2/home/Books:/cwa-book-ingest
      - /volume2/books:/calibre-library
    ports:
      - 38083:8083
    restart: unless-stopped
```
