### ISSUE TITLE
Ingest Is Failing

### ISSUE THREAD

**Issue by janstadt** [crocodilestick/Calibre-Web-Automated#328]
**Describe the bug**
Using calibre-web-downloader and have it configured to point to the same ingest folder that calibre-web uses. The download happens, calibre-web automatically detects, fixes epub, and then fails trying to import the file into calibre. 

**To Reproduce**
1. Move an epub to ingest folder
2. Look at logs
3. See error

**Expected behavior**
Import works

**Screenshots**

<img width="1209" alt="Image" src="https://github.com/user-attachments/assets/2fe1182c-64fd-4c42-8ae7-cb1bcb80c9b2" />

**Configuration(please complete the following information):**
 - OS: Unraid
 - Hardware: qnap intel
 - Version latest

docker-compose:
```
services:
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    container_name: calibre-web-automated-downloader
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/calibre/ingest:/cwa-book-ingest
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://192.168.1.89:8191
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
      UID: 1000
      GID: 1000
    ports:
      - 8085:8084
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      # - DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre-v7.16.0
    volumes:
      - /mnt/cache/appdata/docker/config/calibre:/config
      - /mnt/cache/appdata/calibre/ingest:/cwa-book-ingest
      # - /mnt/cache/appdata/calibre/tmp:/cwa-import
      # - /path/to/the/folder/you/want/to/use/for/book/ingest:/cwa-book-ingest
      - /mnt/remotes/TOWER_media/library/books:/calibre-library:rw,slave
      #- /path/to/your/gmail/credentials.json:/app/calibre-web/gmail.json #Optional
    ports:
      - 8084:8083 # Change the first number to change the port you want to access the Web UI, not the second
    restart: unless-stopped
```

**Additional context**

Ive tested it out with a number of different PGID/PUID's. Unraid typically uses 99:100 (nobody) so i initially had it as that, but tried to match the docs but got the same result. I also removed the `DOCKER_MODS` section as i didnt see it in the docs any longer. If its required i can throw it back in but with/without did not affect the error i was seeing.

Logs:
```
[cwa-kindle-epub-fixer] Writing EPUB...
[cwa-kindle-epub-fixer] EPUB successfully written.
[cwa-kindle-epub-fixer] Adding run to cwa.db...
[cwa-kindle-epub-fixer] Run successfully added to cwa.db.
[ingest-processor] 9d8078ae5cbf16c7b97d78b3bd9e9801.epub successfully processed with the cwa-kindle-epub-fixer!
[ingest-processor]: Importing new book to CWA...
[ingest-processor] 9d8078ae5cbf16c7b97d78b3bd9e9801 was not able to be added to the Calibre Library due to the following error:
CALIBREDB EXIT/ERROR CODE: 1
```
