### ISSUE TITLE
[bug] /usr/bin/lsiown: Permission denied

### ISSUE THREAD

**Issue by fskaeh** [crocodilestick/Calibre-Web-Automated#335]
**Describe the bug**
When spinning up a calibre-web-automated container for the first time, it fails to initialize due to some permission errors:

```
/run/s6/basedir/scripts/rc.init: 26: /docker-mods: Permission denied
/run/s6/basedir/scripts/rc.init: warning: hook /docker-mods exited 126
[migrations] started
[migrations] no migrations found
groupmod: Permission denied.
groupmod: cannot lock /etc/group; try again later.
usermod: Permission denied.
usermod: cannot lock /etc/passwd; try again later.
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

         ,gggg,                                                                    ,ggg,      gg      ,gg                              
       ,88"""Y8b,             ,dPYb,       ,dPYb,                                 dP""Y8a     88     ,8P          ,dPYb,               
      d8"     `Y8             IP'`Yb       IP'`Yb                                 Yb, `88     88     d8'          IP'`Yb               
     d8'   8b  d8             I8  8I  gg   I8  8I                                  `"  88     88     88           I8  8I               
    ,8I    "Y88P'             I8  8'  ""   I8  8'                                      88     88     88           I8  8'               
    I8'             ,gggg,gg  I8 dP   gg   I8 dP        ,gggggg,   ,ggg,   aaaaaaaa    88     88     88   ,ggg,   I8 dP                
    d8             dP"  "Y8I  I8dP    88   I8dP   88gg  dP""""8I  i8" "8i  """"""""    88     88     88  i8" "8i  I8dP   88gg          
    Y8,           i8'    ,8I  I8P     88   I8P    8I   ,8'    8I  I8, ,8I              Y8    ,88,    8P  I8, ,8I  I8P    8I            
    `Yba,,_____, ,d8,   ,d8b,,d8b,_ _,88,_,d8b,  ,8I  ,dP     Y8, `YbadP'               Yb,,d8""8b,,dP   `YbadP' ,d8b,  ,8I            
      `"Y8888888 P"Y8888P"`Y88P'"Y888P""Y88P'"Y88P"'  8P      `Y8888P"Y888               "88"    "88"   888P"Y8888P'"Y88P"'            


                         █████╗ ██╗   ██╗████████╗ ██████╗ ███╗   ███╗ █████╗ ████████╗███████╗██████╗ 
                        ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗████╗ ████║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗
                        ███████║██║   ██║   ██║   ██║   ██║██╔████╔██║███████║   ██║   █████╗  ██║  ██║
                        ██╔══██║██║   ██║   ██║   ██║   ██║██║╚██╔╝██║██╔══██║   ██║   ██╔══╝  ██║  ██║
                        ██║  ██║╚██████╔╝   ██║   ╚██████╔╝██║ ╚═╝ ██║██║  ██║   ██║   ███████╗██████╔╝
                        ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═════╝ 


                             ~~~ Based on images from linuxserver.io & Calibre-Web by janeczku ~~~

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    1000
───────────────────────────────────────

/etc/s6-overlay/s6-rc.d/init-adduser/run: line 30: /usr/bin/lsiown: Permission denied
/etc/s6-overlay/s6-rc.d/init-adduser/run: line 31: /usr/bin/lsiown: Permission denied
/etc/s6-overlay/s6-rc.d/init-adduser/run: line 32: /usr/bin/lsiown: Permission denied
s6-rc: warning: unable to start service init-adduser: command exited 126
```

**Configuration:**
Running Orbstack on MacOS, my UID/GID are kinda forced by the OS to 501/20, so I set those values in the docker-compose file:

```
name: calibre-web-automated
services:
  calibre-web-automated:
    container_name: calibre-web-automated
    env_file:
      - $DOCKER_PATH/.env.nosync
      - $DOCKER_PATH/.env
      - $DOCKER_PATH/calibre-web-automated/.env
    image: crocodilestick/calibre-web-automated:latest
    networks:
      - global
    platform: linux/arm64/v8
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
      - $DOCKER_PATH/calibre-web-automated/calibre-web-automated:/config:rw
      - $BOOKS_PATH:/calibre-library:rw
networks:
  global:
    external: true
```

Respectively `PUID=501` and `GID=20` as verifiable from inside the container:

```
I have no name!@26777e621d36:/$ env
...
PUID=501
PGID=20
```

Oddly enough, as you can see in the startup log, it got 911/1000 for the user UID and GID, which I don't really understand. I have some other containers that complain about using values other than 1000:1000 (namely postgresql containers) but usually forcing it via the `user` property in the docker-compose file is enough to shut them up and make them work. Here it doesn't seem to be doing the trick unfortunately. Any idea how to proceed?
