### ISSUE TITLE
[bug] Auto ingest on 3.0.4 doesn't seem to work without universal-calibre DOCKER MOD

### ISSUE THREAD

**Issue by hjdarnel** [crocodilestick/Calibre-Web-Automated#390]
**Describe the bug**
I drop an epub file into my auto ingest folder, I expect refreshing the library to import it but it doesn't. It does seem to work if I set the DOCKER_MODS environment variable again.

**To Reproduce**
1. Setup docker compose using provided file
<details><summary>docker compose</summary>
<p>

```
---
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      # Only change these if you know what you're doing
      - PUID=1000
      - PGID=1000
      # Edit to match your current timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=UTC 
    volumes:
      # CW users migrating should stop their existing CW instance, make a copy of the config folder, and bind that here to carry over all of their user settings ect.
      - /path/to/config/folder:/config 
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      - /path/to/the/folder/you/want/to/use/for/book/ingest:/cwa-book-ingest
      # If you don't have an existing library, CWA will automatically create one at the bind provided here
      - /path/to/your/calibre/library:/calibre-library 
    ports:
      # Change the first number to change the port you want to access the Web UI, not the second
      - 8083:8083 
    restart: unless-stopped
```

</p>
</details> 

2. (cwa is configured correctly otherwise)
3. drop .epub in monitored folder
4. click refresh library

**Expected behavior**
You expect it to import, it doesn't

Adding the docker mod seems to work again, though I see the commits to no longer need it...
