### ISSUE TITLE
[bug] Issue after docker setup (cannot login)

### ISSUE THREAD

**Issue by hmorandell** [crocodilestick/Calibre-Web-Automated#396]
**Describe the bug**
I deployed the container with the following compose file:
```
---
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8083 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      # Only change these if you know what you're doing
      - PUID=1004
      - PGID=1004
      # Edit to match your current timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/Rome 
    volumes:
      # CW users migrating should stop their existing CW instance, make a copy of the config folder, and bind that here to carry over all of their user settings ect.
      - /opt/cwa/config:/config 
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      - /opt/cwa/ingest:/cwa-book-ingest
      # If you don't have an existing library, CWA will automatically create one at the bind provided here
      - /opt/cwa/library:/calibre-library 
    ports:
      # Change the first number to change the port you want to access the Web UI, not the second
      - 4987:8083 
    restart: unless-stopped
```

I use nginx as reverse proxy. The site is loading up correctly (SSL has been done via letsencrypt), but the login does not work, as soon as I try to signin the browser is just loading and nothing happens.

**Expected behavior**

**Configuration(please complete the following information):**
 - OS: Ubuntu 24.04

**Additional context**
this are the logs I see in the docker:
```
[migrations] started
[migrations] no migrations found
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
         ,gggg,                                                                    ,ggg,      gg      ,gg                              
       ,88"""Y8b,             ,dPYb,       ,dPYb,                                 dP""Y8a     88     ,8P          ,dPYb,               
      d8"     `Y8             IP'`Yb       IP'`Yb                                 Yb, `88     88     d8'          IP'`Yb               
     d8'   8b  d8             I8  8I  gg   I8  8I                                  `"  88     88     88           I8  8I               
    ,8I    "Y88P'             I8  8'  ""   I8  8'                                      88     88     88           I8  8'               
    I8'             ,gggg,gg  I8 dP   gg   I8 dP        ,gggggg,   ,ggg,   aaaaaaaa    88     88     88   ,ggg,   I8 dP                
    d8             dP"  "Y8I  I8dP    88   I8dP   88gg  dP""""8I  i8" "8i  """"""""    88     88     88  i8" "8i  I8dP   88gg          
    Y8,           i8'    ,8I  I8P     88   I8P    8I   ,8'    8I  I8, ,8I              Y8    ,88,    8P  I8, ,8I  I8P    8I            
    `Yba,,_____, ,d8,   ,d8b,,d8b,_ _,88,_,d8b,  ,8I  ,dP     Y8, `YbadP'               Yb,,d8""8b,,dP   `YbadP' ,d8b,  ,8I            
      `"Y8888888 P"Y8888P"`Y88P'"Y888P""Y88P'"Y88P"'  8P      `Y8888P"Y888               "88"    "88"   888P"Y8888P'"Y88P"'            
                         █████╗ ██╗   ██╗████████╗ ██████╗ ███╗   ███╗ █████╗ ████████╗███████╗██████╗ 
                        ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗████╗ ████║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗
                        ███████║██║   ██║   ██║   ██║   ██║██╔████╔██║███████║   ██║   █████╗  ██║  ██║
                        ██╔══██║██║   ██║   ██║   ██║   ██║██║╚██╔╝██║██╔══██║   ██║   ██╔══╝  ██║  ██║
                        ██║  ██║╚██████╔╝   ██║   ╚██████╔╝██║ ╚═╝ ██║██║  ██║   ██║   ███████╗██████╔╝
                        ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═════╝ 
                             ~~~ Based on images from linuxserver.io & Calibre-Web by janeczku ~~~
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1004
User GID:    1004
───────────────────────────────────────
[custom-init] No custom files found, skipping...
/etc/s6-overlay/s6-rc.d/universal-calibre-setup/run: line 20: calibredb: command not found
[universal-calibre-setup] USER NOTE: 'Ignore calibredb: command not found' above, nothing is wrong, this just indicates to CWA that Calibre still needs to be installed
[universal-calibre-setup] Installing Calibre version 7.16.0...
[cwa-init] Checking for leftover lock files from previous instance...
[cwa-init] No leftover lock files to remove. Ending service...
[cwa-init] Checking for an existing app.db in /config...
[cwa-init] Existing app.db found!
[cwa-init] Setting binary paths in '/config/app.db' to the correct ones...
[cwa-init] Successfully set binary paths in '/config/app.db'!
[cwa-init] CWA-init complete! Service exiting now...
[cwa-init] Recursively setting ownership of everything in /config, /calibre-library, /app/calibre-web-automated to abc:abc...
[cwa-init] Successfully set permissions for '/config'!
[cwa-init] Successfully set permissions for '/calibre-library'!
[cwa-init] Successfully set permissions for '/app/calibre-web-automated'!
[cwa-auto-zipper] Starting CWA-Auto-Zipper service...
[cwa-auto-zipper] Matching internal localtime & timezone with the one provided...
[cwa-auto-zipper] Zoneinfo for Europe/Rome found. Setting /etc/localtime and /etc/timezone to match...
[cwa-auto-zipper] Timezone & Localtime successfully set to Europe/Rome. Initiating Auto-Zipper ...
[cwa-auto-library]: Existing library found at /calibre-library, mounting now...
[cwa-auto-library] Updating dirs.json with new library location...
[cwa-auto-library]: Updating Settings Database with library location...
[cwa-auto-library] Library location successfully set to: /calibre-library
[cwa-auto-zipper] Next run in 27590 seconds.
========== STARTING CWA-INGEST SERVICE ==========
========== STARTING METADATA CHANGE DETECTOR ===========
[metadata-change-detector] Watching folder: /app/calibre-web-automated/metadata_change_logs
[cwa-ingest-service] Watching folder: /cwa-book-ingest
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
Setting up watches.
Watches established.
[universal-calibre-setup] Calibre setup completed successfully! Exiting now...
[ls.io-init] done.
```
