### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Taubin** [crocodilestick/Calibre-Web-Automated#410]
**Describe the bug**
Kepubify has the incorrect binary on arm64

**To Reproduce**

    Run initial docker compose on arm64
    Upload a book
    Go to edit metadata
    Convert to kepub
    Go to tasks and see error

**Expected behavior**
Book should be converted

**Configuration(please complete the following information):**
 - OS: Debian arm64
 - Hardware: Pi5

**Additional context**
bashing in to the container and attempting to run kepubify on a pi5 gives the following error:

```
root@c39ba8672118:~# kepubify
bash: /usr/bin/kepubify: cannot execute binary file: Exec format error
```
Error in the application
```
Convert: EPUB -> KEPUB: Classic Goosebumps Collection: Books 1-4	Failed	100 %	0s	6/29/25, 9:55 PM	Kepubify-converter failed: [Errno 8] Exec format error: '/usr/bin/kepubify'	
```

Version information:
```
Calibre-Web Automated 	V3.0.4 	Current Version
Stock Calibre-Web 	0.6.24 	Current Version
Linuxserver.io 	0.6.24-ls304 	Current Version
Calibre 	7.16.0 	-
Kepubify 	v4.0.4 
```
Docker compose if needed:
```
---
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      # Only change these if you know what you're doing
      - PUID=1000
      - PGID=1000
      # Edit to match your current timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Pacific/Auckland
    volumes:
      # CW users migrating should stop their existing CW instance, make a copy of the config folder, and bind that here to carry over all of their user settings ect.
      - ~/config:/config
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      - ~/calibre/calibre-ingest:/cwa-book-ingest
      # If you don't have an existing library, CWA will automatically create one at the bind provided here
      - ~/calibre/calibre-library:/calibre-library
    ports:
      # Change the first number to change the port you want to access the Web UI, not the second
      - 8083:8083
    restart: unless-stopped
```
