### ISSUE TITLE
[Issue Under Investigation] Issues when converting exisitng library

### ISSUE THREAD

**Issue by truthsword** [crocodilestick/Calibre-Web-Automated#58]
`convert-library -k`

Every book yielded:
```
[convert-library]: (861/908)  Converting Superior Justice - Tom Hilpert.azw3...
cp: cannot create regular file '/config/original-library/Superior Justice - Tom Hilpert.azw3': No such file or directory
Cannot read from /config/original-library/Superior Justice - Tom Hilpert.azw3
```

What am I doing wrong?

**Comment by iroQuai** [comment]
Can you give some more context? Maybe share your compose file, tell us what version you are on and on what kind of system? (For instance, NAS systems like Synology give additional issues sometimes). And are your permissions in order (via PGID/PUID)?

**Comment by truthsword** [comment]
Running docker on Debian 12. Container features appear to be working (I'm still evaluating). 

Note: Before launching the compose, I copied my existing Calibre Library (including metadata file) to the library directory (myLibrary) used in the compose file. Since much of the liibrary appeared, at launch, with its metadata, this appears to be OK.

Compose:
```
services:
  calibre-wa:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-wa
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    ports:
      - 8083:8083
    volumes:
      - ./config;/config
      - ./ingest:/cwa-book-ingest
      - ./myLibrary:/calibre-library
```
Opened terminal and tested `convert-library -h` and response seemed correct, then moved on to `convert-library -k` and had 900+ failures.

Later I manually added `original-library` directory under `config`, and no response.

Before posting here, I downed the container, deleted all content in `config` and `myLibrary` and then restarted the compose file, with the same result with `convert-library`. EXCEPT... now the total count was 1816 errors, precisely twice the original. So I suspect I did not clean out all volumes?
