### ISSUE TITLE
[bug] Removing config data, still created database in old path

### ISSUE THREAD

**Issue by newdamage1** [crocodilestick/Calibre-Web-Automated#74]
**Describe the bug**
Not 100% this is a bug, human error...

The database is recreated in the old location, even after the compose file is changed, and the /config file is cleared.

**To Reproduce**

Stop container.

Removing the old calibre database path :

       - /data/E-books/calibre_old:/calibre-library
       
To the new database path :

       - /data/E-books/calibre_new:/calibre-library

Remove all files within : 

       - /docker/appdata/calibre-web-automated/config

Restart container

The calibre_old folder is recreated, with a database.

My compose file looks like this:

```
   calibre-web-automated:
     image: crocodilestick/calibre-web-automated:latest
     container_name: calibre-web-automated
     environment:
       - PUID=xxxx
       - PGID=xxxx
       - TZ=America/New_York
       - DOCKER_MODS=linuxserver/mods:universal-calibre
     volumes:
       - /docker/appdata/calibre-web-automated/config:/config
       - /data/E-books/calibre_new:/calibre-library
     ports:
       - 8069:8083 
     restart: unless-stopped
```

**Expected behavior**
I would expect it would use the new configuration path.

**Screenshots**

**Configuration(please complete the following information):**
 - OS:  Ubuntu Server 
 - Hardware: vmware guest
 - Version 2404

**Additional context**
