### ISSUE TITLE
[bug] Separate Book Files from Library

### ISSUE THREAD

**Issue by tucker87** [crocodilestick/Calibre-Web-Automated#92]
**Description**
Split metadata/books options is not being respected

**To Reproduce**
- New Instance using this
```yaml
calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=100
      - TZ=UTC
      - DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre-v7.16.0
    volumes:
      - ${CONFIG_ROOT:-.}/calibre/config-cwa:/config
      - ${CONFIG_ROOT:-.}/calibre/config-cwa/calibre-library:/calibre-library
      - ${APPHOME_ROOT}/book-ingest:/cwa-book-ingest
      - ${DATA_ROOT}/books:/books
    ports:
      - 8084:8083
```
- Set database config to use /calibre-library and /books
![image](https://github.com/user-attachments/assets/e68dc168-244c-4901-ac61-cabb3d09e7f2)
- Copy files into cwa-book-inject
- Click Refresh Library

**Expected behavior**
Books should be in /books but are ending up in the /calibre-library

**Unexpected behavior**
Setting the database config as above breaks the cover images 
Downloads 404

**Configuration(please complete the following information):**
 - OS: Ubuntu Server
 - Hardware: x86 server
 - Version: Latest?

**Additional context**
No original database/config. I've removed the config dir and started over with each test

CONFIG_ROOT is local
Other *_ROOTS are on NAS
