### ISSUE TITLE
s6-rc-oneshot-run: fatal: unable to exec /etc/s6-overlay/s6-rc.d/init-mods-package-install/run: Exec format error

### ISSUE THREAD

**Issue by davidclaeysquinones** [crocodilestick/Calibre-Web-Automated#95]
I'm using the following compose file :

```yaml
version: "2.1"
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      #- DOCKER_MODS=linuxserver/mods:universal-calibre
      - DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre-v7.16.0
    volumes:
      - ${CONFIG_FOLDER}:/config
      - ${UPLOAD_FOLDER}:/cwa-book-ingest
      - ${PLUGIN_FOLDER}:/plugins 
      - ${LIBRARY_FOLDER}:/calibre-library
      #- /path/to/where/you/keep/your/books:/books #Optional
      #- /path/to/your/gmail/credentials.json:/app/calibre-web/gmail.json #Optional
    ports:
      - 8083:8083 # Change the first number to change the port you want to access the Web UI, not the second
    restart: unless-stopped
```

When I deploy the file the container is created and started.
But at startup I get the following error :

`s6-rc-oneshot-run: fatal: unable to exec /etc/s6-overlay/s6-rc.d/init-mods-package-install/run: Exec format error`

I get this with image _sha256:953fa618fce315d1477a0896261954133d7ee0958f4aabe4444d46c8543e028f_ 

I haven't noticed other people having the same error so either I'm doing something wrong or experiencing an unknown issue.
