### ISSUE TITLE
[bug] new-book-processor initiated but is already running

### ISSUE THREAD

**Issue by anantone** [crocodilestick/Calibre-Web-Automated#98]
When adding a new book to the "ingest" folder, this message appears:
```
[books-to-process]: New files detected - /cwa-book-ingest/The Tartan Turban_ In Search of Alexander - John Keay.epub

CANCELING... new-book-processor initiated but is already running

[books-to-process]: New files successfully moved/converted, the Ingest Folder has been emptied and is ready to go again.
```

What happens instead is the file remains in the ingest folder, and is not added to the library.

I'm running the latest Docker image on Ubuntu 24.04 with the compose file below. Permissions are coherent throughout. 

I've tried restarting the container with an empty ingest folder, then adding the file; restarting the container with the file already in the ingest folder... Nothing doing. Not able to import books through ingest folder.

```
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: cwa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /root/cwa/config:/config
      - /root/cwa/ingest:/cwa-book-ingest
      - /root/cwa/calibre-library:/calibre-library
      #- /path/to/where/you/keep/your/books:/books #Optional
      #- /path/to/your/gmail/credentials.json:/app/calibre-web/gmail.json #Optional
    ports:
      - 127.0.0.1:8784:8083 # Change the first number to change the port you want to access the Web UI, not the second
    networks:
      - pont
    restart: unless-stopped
networks:
  pont:
    external: true
```
